name: Format, lint and build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      # Install dependencies
      - run: bun install
      # Check format
      - run: bun run format:check
      # Lint
      - run: bun run lint
      # Build
      - run: bun run build
